# Generated by Django 4.1.3 on 2022-12-02 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 16, 46, 23, 551775)),
        ),
    ]
