# Generated by Django 4.1.3 on 2022-12-04 09:48

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0005_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 4, 14, 48, 2, 676819)),
        ),
    ]
