# Generated by Django 4.1.3 on 2022-12-10 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0011_note_tags_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 12, 44, 254681)),
        ),
    ]
