# Generated by Django 4.1.4 on 2022-12-16 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0014_alter_note_date_alter_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uploadedFile',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 14, 44, 6, 511199)),
        ),
    ]
